services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container_beneficios
    ports:
      - 80:8080
    volumes:
      - ./APIDoc.yaml:/usr/share/nginx/html/doc/APIDoc.yaml
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/doc/APIDoc.yaml

  spring-beneficios:
    container_name: spring_beneficios
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SPRING_APPLICATION_NAME: Spring_Beneficios
      SPRING_JPA_HIBERNATE.DDL_AUTO: update
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-beneficios:${PGPORT}/DatabaseBeneficios
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - 8082:8080
    depends_on:
      - db-beneficios

  db-beneficios:
    container_name: db_beneficios
    image: postgres:16.2
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: DatabaseBeneficios
      PGPORT: ${PGPORT}
    ports:
      - ${PGPORT}:5432
    env_file:
      .env

volumes:
  db-auth:
  db-data:
