services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - 80:8080
    volumes:
      - ./APIDoc.yaml:/usr/share/nginx/html/doc/APIDoc.yaml
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/doc/APIDoc.yaml
  spring:
    container_name: spring_container
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SPRING_APPLICATION_NAME: Beneficios
      SPRING_JPA_HIBERNATE.DDL_AUTO: update
      SPRING_DATASOURCE_URL: jdbc:postgresql://psql:${PGPORT}/GerenciaBeneficios
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8082:8080
    env_file:
      .env
    depends_on:
      - psql

  psql:
    container_name: postgres_container
    image: postgres:16.2
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: GerenciaBeneficios
      PGPORT: ${PGPORT}
    ports:
      - ${PGPORT}:${PGPORT}
    env_file:
      .env

volumes:
  db-data:
