services:
  spring:
    container_name: spring_container
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SPRING_APPLICATION_NAME: Beneficios
      SPRING_JPA_HIBERNATE.DDL_AUTO: update
      SPRING_DATASOURCE_URL: jdbc:postgresql://psql:${PGPORT}/GerenciaBeneficios
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - 8080:8082
    env_file:
      - ./.env

  psql:
    container_name: postgres_container
    image: postgres:alpine3.18
    volumes:
      - ./src/main/java/scripts/script.sql:/docker-entrypoint-initdb.d/script.sql
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: GerenciaBeneficios
      PGPORT: ${PGPORT}
    ports:
      - ${PGPORT}:${PGPORT}
    env_file:
      - ./.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    env_file:
      - ./.env
volumes:
  db_data:
