version: "3"
services:
  react-node:
    container_name: react-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5300:5300"
    volumes:
      - node_modules:./node_modules
volumes:
  node_modules: